spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb:http://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**
        #            filters:
        #              - PrefixPath=/api/v1/customers/**
        - id: order-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
        #            filters:
        #              - PrefixPath=/api/v1/orders/**
        - id: order-line-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order-lines/**
        #            filters:
        #              - PrefixPath=/api/v1/order-lines/**
        - id: payment-service
          uri: lb:http://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**
        #            filters:
        #              - PrefixPath=/api/v1/payments/**
        - id: product-service
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
        #            filters:
        #              - PrefixPath=/api/v1/products/**

server:
  port: 8222
