spring:
  data:
    mongodb:
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      host: ${DB_URL}
      port: ${DB_PORT}
      authentication-database: ${DB_USERNAME}
      database: ${DB_NAME}

  mail:
    host: localhost
    port: 1025
    username: ${MAIL_DEV_USERNAME}
    password: ${MAIL_DEV_PASSWORD}
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connection-timeout: 5000
        timeout: 3000
        write-timeout: 5000

server:
  port: 8040